import type { IntegrationProvider, AiProviderConfig, PublishingAccount } from './types';

export const DATA_SOURCE_PROVIDERS: IntegrationProvider[] = [
  {
    id: 'google-trends',
    platformKey: 'gt',
    name: 'Google Trends',
    status: 'demo',
    authType: 'server_adapter',
    scopes: [
      { name: 'trends:read', description: 'Read public trending searches', required: true },
    ],
    lastSync: '2m ago',
    secretStorageMode: 'none',
    backendConnectEndpoint: '/api/integrations/connect/google-trends',
    backendStatusEndpoint: '/api/integrations/status/google-trends',
  },
  {
    id: 'youtube',
    platformKey: 'yt',
    name: 'YouTube Shorts',
    status: 'demo',
    authType: 'api_key',
    scopes: [
      { name: 'youtube.readonly', description: 'Read public video metadata', required: true },
      { name: 'youtube.force-ssl', description: 'Enforce HTTPS on all requests', required: true },
    ],
    lastSync: '4m ago',
    secretStorageMode: 'backend_encrypted',
    backendConnectEndpoint: '/api/integrations/connect/youtube',
    backendStatusEndpoint: '/api/integrations/status/youtube',
  },
  {
    id: 'tiktok',
    platformKey: 'tt',
    name: 'TikTok',
    status: 'demo',
    authType: 'oauth2',
    scopes: [
      { name: 'research.data.basic', description: 'Access public video and creator data', required: true },
      { name: 'research.adlib.basic', description: 'Trending content signals', required: false },
    ],
    lastSync: '3m ago',
    secretStorageMode: 'backend_encrypted',
    backendConnectEndpoint: '/api/integrations/connect/tiktok',
    backendStatusEndpoint: '/api/integrations/status/tiktok',
  },
  {
    id: 'instagram',
    platformKey: 'ig',
    name: 'Instagram Reels',
    status: 'demo',
    authType: 'oauth2',
    scopes: [
      { name: 'instagram_basic', description: 'Read hashtag and post metadata', required: true },
      { name: 'pages_read_engagement', description: 'Reach and engagement signals', required: false },
    ],
    lastSync: '9m ago',
    secretStorageMode: 'backend_encrypted',
    backendConnectEndpoint: '/api/integrations/connect/instagram',
    backendStatusEndpoint: '/api/integrations/status/instagram',
  },
  {
    id: 'facebook',
    platformKey: 'fb',
    name: 'Facebook Reels',
    status: 'demo',
    authType: 'oauth2',
    scopes: [
      { name: 'public_content', description: 'Read public Reels content signals', required: true },
    ],
    lastSync: '1h ago',
    secretStorageMode: 'backend_encrypted',
    backendConnectEndpoint: '/api/integrations/connect/facebook',
    backendStatusEndpoint: '/api/integrations/status/facebook',
  },
  {
    id: 'twitter',
    platformKey: 'x',
    name: 'X / Twitter',
    status: 'demo',
    authType: 'api_key',
    scopes: [
      { name: 'tweet.read', description: 'Read public tweets and trending topics', required: true },
      { name: 'users.read', description: 'Read public user metadata', required: true },
    ],
    lastSync: '21m ago',
    secretStorageMode: 'backend_encrypted',
    backendConnectEndpoint: '/api/integrations/connect/twitter',
    backendStatusEndpoint: '/api/integrations/status/twitter',
  },
  {
    id: 'threads',
    platformKey: 'th',
    name: 'Threads',
    status: 'demo',
    authType: 'oauth2',
    scopes: [
      { name: 'threads_basic', description: 'Read public thread content', required: true },
    ],
    lastSync: '41m ago',
    secretStorageMode: 'backend_encrypted',
    backendConnectEndpoint: '/api/integrations/connect/threads',
    backendStatusEndpoint: '/api/integrations/status/threads',
  },
];

export const AI_PROVIDERS: AiProviderConfig[] = [
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    status: 'demo',
    model: 'claude-sonnet-4-6',
    usageMode: 'demo',
    secretStorageMode: 'backend_encrypted',
    backendEndpoint: '/api/ai/anthropic',
    contextWindow: '200K tokens',
    costNote: 'API key stored server-side only. Never expose in browser bundle or VITE_ vars.',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    status: 'not_connected',
    model: 'gpt-4o',
    usageMode: 'demo',
    secretStorageMode: 'backend_encrypted',
    backendEndpoint: '/api/ai/openai',
    contextWindow: '128K tokens',
    costNote: 'API key stored server-side only. Never expose in browser bundle or VITE_ vars.',
  },
  {
    id: 'local-mock',
    name: 'Local / Mock Generator',
    status: 'connected',
    model: 'mock-generator-v1',
    usageMode: 'local',
    secretStorageMode: 'none',
    backendEndpoint: '/api/ai/local',
    contextWindow: 'N/A',
    costNote: 'No secrets required. Generates deterministic demo content from static templates.',
  },
];

export const PUBLISHING_ACCOUNTS: PublishingAccount[] = [
  {
    id: 'pub-youtube',
    platformKey: 'yt',
    name: 'YouTube Shorts',
    handle: null,
    status: 'not_connected',
    uploadPermission: false,
    publishPermission: false,
    tokenExpiry: null,
    tokenStatus: 'none',
    defaultPrivacy: 'public',
    defaultHashtags: ['#shorts', '#youtube'],
    defaultPostTime: null,
    backendConnectEndpoint: '/api/publish/connect/youtube',
  },
  {
    id: 'pub-tiktok',
    platformKey: 'tt',
    name: 'TikTok',
    handle: null,
    status: 'not_connected',
    uploadPermission: false,
    publishPermission: false,
    tokenExpiry: null,
    tokenStatus: 'none',
    defaultPrivacy: 'public',
    defaultHashtags: ['#fyp', '#tiktok'],
    defaultPostTime: null,
    backendConnectEndpoint: '/api/publish/connect/tiktok',
  },
  {
    id: 'pub-instagram',
    platformKey: 'ig',
    name: 'Instagram Reels',
    handle: null,
    status: 'not_connected',
    uploadPermission: false,
    publishPermission: false,
    tokenExpiry: null,
    tokenStatus: 'none',
    defaultPrivacy: 'public',
    defaultHashtags: ['#reels', '#instagram'],
    defaultPostTime: null,
    backendConnectEndpoint: '/api/publish/connect/instagram',
  },
  {
    id: 'pub-facebook',
    platformKey: 'fb',
    name: 'Facebook Reels',
    handle: null,
    status: 'not_connected',
    uploadPermission: false,
    publishPermission: false,
    tokenExpiry: null,
    tokenStatus: 'none',
    defaultPrivacy: 'public',
    defaultHashtags: ['#reels'],
    defaultPostTime: null,
    backendConnectEndpoint: '/api/publish/connect/facebook',
  },
  {
    id: 'pub-twitter',
    platformKey: 'x',
    name: 'X / Twitter',
    handle: null,
    status: 'not_connected',
    uploadPermission: false,
    publishPermission: false,
    tokenExpiry: null,
    tokenStatus: 'none',
    defaultPrivacy: 'public',
    defaultHashtags: [],
    defaultPostTime: null,
    backendConnectEndpoint: '/api/publish/connect/twitter',
  },
  {
    id: 'pub-threads',
    platformKey: 'th',
    name: 'Threads',
    handle: null,
    status: 'not_connected',
    uploadPermission: false,
    publishPermission: false,
    tokenExpiry: null,
    tokenStatus: 'none',
    defaultPrivacy: 'public',
    defaultHashtags: [],
    defaultPostTime: null,
    backendConnectEndpoint: '/api/publish/connect/threads',
  },
];
